name: terraform-lint

on: [ push, pull_request ]

jobs:
  k8s-lint:
    name: Lint Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run k8s-lint
        uses: azure/k8s-lint@v1
        with:
          manifests: |
            k8s/*.yaml
