name: terraform-lint

on: [ push, pull_request ]

jobs:
  k8s-lint:
    name: Lint Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: k8s
          config: .github/kube-linter-config.yaml
